c_compiler_version:         # [unix]
  - 15                      # [linux]
  - 20                      # [osx]
cxx_compiler_version:       # [unix]
  - 15                      # [linux]
  - 20                      # [osx]
fortran_compiler_version:
  - 15                      # [unix]
  - 20                      # [win]
